apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

    spec:
      containers:
      - name: app
        image: europe-north1-docker.pkg.dev/serene-bliss-499420-p4/my-app-repo/demo-app:eb03bd6969a7cda18256da59d2b06dc7416b8b8f
        imagePullPolicy: Always
        ports:
        - containerPort: 5000