name: Deploy

on:
  push:
    branches:
      - main
      - staging
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Set environment path
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Terraform Init
        run: |
          cd environments/${{ env.ENV }}
          terraform init

      - name: Terraform Apply
        run: |
          cd environments/${{ env.ENV }}
          terraform apply -auto-approve